name: quansuanlingshou
on:
  workflow_dispatch:
  schedule:
    - cron: '18 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: quansuanlingshou
        env:
          muqum594: ${{ secrets.muqum594 }}
        run: |
          echo $muqum594 | jq -r .dazas80 | /bin/bash
          echo $qcbtu0973 | jq -r .kmir5855 | /bin/bash
          echo $n951 | jq -r .nl7 | /bin/bash

